on:
  workflow_dispatch:
  schedule:
    - cron: '20 1 * * *'
name: Update AriaNg
jobs:
  check:
    name: Check new release
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.compare.outputs.updated }}
      tag: ${{ steps.compare.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compare tags
        id: compare
        run: |
          export LATEST=$(curl -s 'https://api.github.com/repos/mayswind/AriaNg/releases/latest' | jq '.tag_name' | tr -d '"')
          echo "::set-output name=tag::${LATEST}"
          export DEPLOYED="0"
          if test -f version.txt; then export DEPLOYED=$(cat version.txt); fi
          if [ $LATEST == $DEPLOYED ]; then echo "::set-output name=updated::true"; else echo "::set-output name=updated::false"; fi

  deploy:
    name: Deploy the web
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Download AriaNg latest release
        env:
          UPDATED: ${{ needs.check.outputs.updated }}
          TAG: ${{ needs.check.outputs.tag }}
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "mayswind/AriaNg"
          latest: true
          fileName: "AriaNg-${TAG}.zip"

      - name: Unzip and create version file
        env:
          TAG: ${{ needs.check.outputs.tag }}
        run: unzip AriaNg-${TAG}.zip -d public && echo ${TAG} > public/version.txt

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
